apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
spec:
  ingressClassName: alb
  rules:
    # As the images are from docker hub and the app in it works on / path we are not using path based routing here.
    # We are using host based routing to route the traffic to the respective services.
    - host: vote.905418456360.realhandsonlabs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-app-service
                port:
                  number: 80

    - host: result.905418456360.realhandsonlabs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: result-service
                port:
                  number: 80